### PR TITLE
Added member

### PR DESCRIPTION
**Pull request by tigercxx**
Added Xian Xiang

### CODE REVIEW

**Comment by Yohuan** [comment]
Please remove the unnecessary indent.

**Comment by tigercxx** [comment]
> Please remove the unnecessary indent.

Apologies, my editor auto-formatted. I've disabled auto-formatting on markdown files. Have made the necessary changes.

**Comment by Yohuan** [comment]
@tigercxx Please resolve the conflict.

**Comment by tigercxx** [comment]
Conflict resolved

**Pull request merged**
