### PR TITLE
Ran flutter create (default app)

### PR DESCRIPTION
**Pull request by tigercxx**
Can try to checkout my branch then see if all of you can run. Hopefully my versioning should be the most updated one already. Lmk if have any issues! Once all okay then can merge to main and can start building bah

### CODE REVIEW

**Comment by Yohuan** [comment]
Can u put on the link of the resource u followed to make this default app? thanks

**Comment by Yohuan** [comment]
Also can record a video and convert it to gif. Put gif into PR description or comment so that the reviewer could immediately get a sense of the change.

**Comment by tigercxx** [comment]
Hi, i just ran flutter create within the folder. It is the default flutter app.
Also, what do you mean by record a video? What should the content of the video be?

**Comment by Jaylin0312** [comment]
ltgm ..

**Pull request closed without merging**
